# Generated by Django 3.2.10 on 2022-03-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20220317_0725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtags', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='hashtags',
            field=models.ManyToManyField(blank=True, to='posts.Tags'),
        ),
    ]
