# Generated by Django 3.2.10 on 2022-03-24 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20220324_0726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='hashtags',
            new_name='tag',
        ),
    ]
