# Generated by Django 3.2.10 on 2022-02-21 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='contact_details',
        ),
    ]
